name: 'Update README with deployment info'

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

env:
  PROJECT_ID: 'tugidoko-dev'
  REGION: 'asia-northeast1'
  SERVICE: 'nginx-app'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/109380428695/locations/global/workloadIdentityPools/github-pool/providers/github-provider' # TODO: update to your workload identity provider

jobs:
  update-readme:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@f0990588f1e5b5af6827153b93673613abdc6ec7'
      
      - name: 'Get Cloud Run image info'
        id: 'image-info'
        run: |-
          IMAGE=$(gcloud run services describe "${{ env.SERVICE }}" \
            --region="${{ env.REGION }}" \
            --project="${{ env.PROJECT_ID }}" \
            --format='value(spec.template.spec.containers[0].image)')
          echo "image=${IMAGE}" >> $GITHUB_OUTPUT
          
          DIGEST=$(gcloud container images describe "${IMAGE}" \
            --format='value(image_summary.digest)')
          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT
          
          DIGEST_SHORT=$(echo "${DIGEST}" | sed 's/^sha256://' | cut -c1-7)
          echo "digest_short=${DIGEST_SHORT}" >> $GITHUB_OUTPUT
          
          echo "Full digest: ${DIGEST}"

      - name: 'Update README'
        run: |-
          perl -i -pe 'BEGIN{undef $/;} s|<!-- DEPLOY_DIGEST -->.*?<!-- /DEPLOY_DIGEST -->|<!-- DEPLOY_DIGEST -->\n![Badge](https://img.shields.io/badge/Image%20Digest-${{ steps.image-info.outputs.digest_short }}-green?logo=docker)\n<!-- /DEPLOY_DIGEST -->|gs' README.md

      - name: 'Commit changes'
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase origin main
          git add README.md
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "chore: update deployment info [skip ci cd]" && git push)